### ISSUE TITLE
Attribution

### ISSUE THREAD

**Issue by vivlim** [uglyoldbob/egui-multiwin#1]
Hi, since this is [published on crates.io](https://crates.io/crates/egui-multiwin) with you listed as the sole author, I would appreciate some form of attribution in the readme referring to my initial work in [egui-glow-multiwin](https://github.com/vivlim/egui-glow-multiwin) that brought together [min_gl_fb's multi_window.rs implementation](https://github.com/shivshank/mini_gl_fb/blob/master/examples/multi_window.rs) and egui, since there was some nontrivial investigation involved in making the windows behave correctly and sharing state between them.

**Comment by uglyoldbob** [comment]
Oh that's no problem at all.

**Comment by uglyoldbob** [comment]
I added a pull request for the change in the readme. Please check it over and let me know if you would like it to be worded differently. #2
