### ISSUE TITLE
Crash when minimizing window

### ISSUE THREAD

**Issue by fitso-2120** [uglyoldbob/egui-multiwin#9]
Hi, I was able to avoid this using the following method.

Error location:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', .../egui-multiwin-0.1.9/src/tracked_window.rs:72:32

Looking at lines 583-584 of egui/crates/eframe/src/native/run.rs, the minimum value is set to 1 when obtaining the height and width.

As a test, I tried doing the same thing around line 71 of egui-multiwin-master/egui-multiwin/src/tracked_window.rs where the height and width are being obtained, and it worked without any abnormal termination.

````
use egui::NumExt;
...
fn resize(&self, size: winit::dpi::PhysicalSize<u32>) {
...
         self.ws.resize(
             &self.context,
             // NonZeroU32::new(w).unwrap(), // comment out
             // NonZeroU32::new(h).unwrap(), // comment out
             NonZeroU32::new(w.at_least(1)).unwrap(), // modified
             NonZeroU32::new(h.at_least(1)).unwrap(), // modified
         )
````

I'm not sure if it's correct to not set it to None when minimized, but I was able to avoid the abnormal termination for the time being.

**Comment by uglyoldbob** [comment]
What system are you experiencing the crash on? I am unable to reproduce it on linux.

**Comment by fitso-2120** [comment]
Windows 11.
Doesn't it happen on Linux?

This may be a problem when absorbing the differences between Windows/Linux in Winit.

I thought they were the same because I was dealing with egui's eframe by setting the minimum width and height to 1.
This may be a long-standing problem.

I will also check the trace in Winit.

**Comment by uglyoldbob** [comment]
I didn't see it on ubuntu. I did reproduce it on my windows 11 machine, so i pushed a commit that includes your fix.

**Comment by fitso-2120** [comment]
Thank you for the quick response.

I confirmed that the egui-multiwin ver-0.1.11 example does not crash when the window is minimized.

Close the issue.
